# Generated by Django 6.0.1 on 2026-05-23 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_category', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('sentiment', models.CharField(max_length=20)),
                ('urgency', models.CharField(max_length=20)),
                ('severity', models.CharField(max_length=20)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.report')),
            ],
        ),
    ]
