# Generated by Django 6.0.1 on 2026-05-29 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issues',
            old_name='issue_category',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='issues',
            name='sentiment',
        ),
        migrations.RemoveField(
            model_name='issues',
            name='severity',
        ),
    ]
