# Generated by Django 6.0.1 on 2026-05-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeuser',
            name='confirm_password',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='officeuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
