# Generated by Django 6.0.1 on 2026-05-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('location', models.CharField(blank=True, max_length=50)),
                ('gps', models.CharField(blank=True, max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='uploads/')),
            ],
        ),
    ]
